Repository ajCadell/TestGitWorkshopTraining, pull requests merged in 2019-11, with the labels that each got.

#12 PROJ-59 Added Favorites file
  Custom/CM/Chad_Favorites.txt
Labels: EX 1

#11 PROJ-56 Added Favorites File
  Custom/MGiles/MGiles_Favorites.txt.txt
Labels: EX 1

#10 PROJ-44: Added favorites.txt
  Custom/JB/JB_Favorites.txt
Labels: EX 1

#9 PROJ-36 Added my favorites file
  Custom/AC/AJ_Favorites.txt
Labels: EX 1

#8 PROJ-42 - Added AG favorites file
  Custom/AGagnon/Agagnon_Favorites.txt
Labels: EX 1

#17 PROJ-66 Updated AG favorites file
  Custom/AGagnon/Agagnon_Favorites.txt
Labels: EX 2

#16 PROJ-53-JH - My Favorites
  Custom/JH/JonHess_Favorites.txt
Labels: EX 1

#22 PROJ-102 Split AG favorites file into likes
  Custom/AGagnon/AG_Favorites.txt
  Custom/AGagnon/AG_Likes.txt
  Custom/AGagnon/Agagnon_Favorites.txt
Labels: EX 3

#25 PROJ-122 AG Repo wide changes
  Custom/AGagnon/AG_Favorites.txt
  Custom/AGagnon/AG_Likes.txt
  Custom/AGagnon/AG_Misc.txt
Labels: EX 4

#21 Added Eggs to my favorite foods
  Custom/MGiles/MGiles_Favorites.txt.txt
Labels: EX 2

#28 PROJ-142 Added AG birthday wish file
  Custom/AGagnon/AG_WishList.txt
Labels: EX 5

#31 Changed the filename of MGiles_Favorites.txt.txt to MGiles_Favorites.txt
  Custom/MGiles/MGiles_Favorites.txt
  Custom/MGiles/MGiles_Likes.txt
Labels: EX 3

#30 PROJ-99 split out likes
  Custom/CM/Chad_Favorites.txt
  Custom/CM/Chad_Likes.txt
Labels: EX 3

#35 PROJ-119 added misc and updated others
  Custom/CM/Chad_Favorites.txt
  Custom/CM/Chad_Likes.txt
  Custom/CM/Chad_Misc.txt
Labels: EX 4

#43 Added Birthday File
  Custom/MGiles/MGiles_Birthday.txt
Labels: EX 5

#41 PROJ-149 added wishlist
  Custom/CM/Chad_wishlist.txt
Labels: EX 5

#45 PROJ-47 Favorite Animal, Food, and Color
  Custom/CRandall/CodyRandall_Favorites.txt
Labels: EX 1

#46 PROJ-43 BB Test
  Custom/BarbBlanchette/BarbBlanchette_Favorites.txt
Labels: EX 1

#47 Case Name - added animal, food and color
  Custom/Marie/Marie_Favorites.txt
Labels: EX 1

#48 PROJ-74 Added Chocolate
  Custom/CRandall/CodyRandall_Favorites.txt
Labels: EX 2

#50 Proj 70
  Custom/BarbBlanchette/BarbBlanchette_Favorites.txt
  Custom/Marie/Marie_Favorites.txt
Labels: EX 2

#51 PROJ-52 added a favorites file
  Custom/AJ2/AJ_Favorites.txt
Labels: EX 1

#54 PROJ-71 added some likes to my favorites file
  Custom/AJ2/AJ_Favorites.txt
Labels: EX 2

#55 PROJ-73 added additional likes to favorites file
  Custom/OA/OA_Favorites.txt
Labels: EX 2

#56 added some likes
  Custom/MCM/Martha_Favorites.txt
Labels: EX 2, label 1 ex 2

#57 PROJ-88 moved my likes into their own file
  Custom/AJ2/AJ_Favorites.txt
  Custom/AJ2/AJ_Likes.txt
Labels: EX 3

#58 PROJ-112 created new file for likes
  Custom/OA/OA_Favorites.txt
Labels: EX 3

#59 Proj 90 martha
  Custom/MCM/Martha_Likes.txt
Labels: EX 3
